const CASES = window.CASES || [];
const state={index:0,points:0,casesSolved:0,view:'dashboard',readDocs:new Set(),analyzedEvidence:new Set(),inspectedHotspots:new Set(),askedQuestions:new Set(),contradictions:new Set(),selectedSuspect:null,theoryEvidence:new Set(),wrongAttempts:0,solved:false,hintUsed:false};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], currentCase=()=>CASES[state.index];

function rankFor(p){return p>=6000?'رئيس وحدة التحقيق':p>=4200?'محقق مخضرم':p>=2800?'خبير جنائي':p>=1700?'محقق أول':p>=900?'محقق ميداني':p>=400?'محقق مبتدئ':'محقق متدرب'}
function esc(t){return String(t??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function resetCaseState(){state.readDocs.clear();state.analyzedEvidence.clear();state.inspectedHotspots.clear();state.askedQuestions.clear();state.contradictions.clear();state.selectedSuspect=null;state.theoryEvidence.clear();state.wrongAttempts=0;state.solved=state.index<state.casesSolved;state.hintUsed=false;const h=$('#hintText');if(h)h.textContent='';const a=$('#accusationMessage');if(a)a.classList.add('hidden')}
function setView(v){state.view=v;$$('.game-view').forEach(x=>x.classList.add('hidden'));const t=$('#view-'+v);if(t)t.classList.remove('hidden');$$('.ops-nav').forEach(b=>b.classList.toggle('active',b.dataset.view===v));if(v==='league')refreshLeaderboard();if(v==='interrogation')renderInterrogation();if(v==='theory')renderTheory();window.scrollTo({top:0,behavior:'smooth'})}

function avatarSVG(s){
  const [skin,hair,coat]=s.palette, uid='p'+[...s.name].reduce((a,c)=>a+c.charCodeAt(0),0)+s.age;
  const k=(s.name.charCodeAt(0)+s.age)%4;
  const hairPath=['M67 83 C70 35 150 30 158 82 C145 61 87 59 67 83Z','M61 88 C60 45 91 27 126 30 C153 32 169 52 164 87 C143 65 93 59 61 88Z','M67 82 C78 38 144 34 160 77 C142 52 95 50 67 82Z','M62 89 C61 47 85 28 119 28 C151 28 171 50 165 88 C145 69 91 63 62 89Z'][k];
  return `<svg viewBox="0 0 220 260" role="img" aria-label="صورة كرتونية ثلاثية الأبعاد للمشتبه ${esc(s.name)}"><defs><linearGradient id="${uid}bg" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#2a3139"/><stop offset="1" stop-color="#0d1014"/></linearGradient><radialGradient id="${uid}skin" cx="38%" cy="28%"><stop stop-color="#f2c4a4"/><stop offset=".55" stop-color="${skin}"/><stop offset="1" stop-color="#8a5d48"/></radialGradient><linearGradient id="${uid}coat" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#65717c"/><stop offset=".45" stop-color="${coat}"/><stop offset="1" stop-color="#171b20"/></linearGradient><filter id="${uid}shadow"><feDropShadow dx="0" dy="8" stdDeviation="7" flood-opacity=".38"/></filter></defs><rect width="220" height="260" fill="url(#${uid}bg)"/><circle cx="38" cy="35" r="58" fill="#f4c927" opacity=".06"/><path d="M35 260 C42 198 75 175 110 175 C151 175 184 199 193 260Z" fill="url(#${uid}coat)" filter="url(#${uid}shadow)"/><path d="M91 170 L82 204 L110 231 L140 202 L130 170Z" fill="#e6e7e9"/><path d="M99 184 L110 231 L121 184 L112 177Z" fill="#222831"/><ellipse cx="112" cy="111" rx="49" ry="63" fill="url(#${uid}skin)" filter="url(#${uid}shadow)"/><ellipse cx="65" cy="115" rx="8" ry="15" fill="${skin}"/><ellipse cx="159" cy="115" rx="8" ry="15" fill="${skin}"/><path d="${hairPath}" fill="${hair}"/><path d="M78 98 Q91 91 101 98M124 98 Q137 91 148 99" fill="none" stroke="#3a2b26" stroke-width="4" stroke-linecap="round"/><ellipse cx="91" cy="107" rx="5" ry="4" fill="#151719"/><ellipse cx="137" cy="107" rx="5" ry="4" fill="#151719"/><circle cx="89" cy="105" r="1.3" fill="#fff"/><circle cx="135" cy="105" r="1.3" fill="#fff"/><path d="M112 108 Q104 129 113 132" fill="none" stroke="#9d6854" stroke-width="3" stroke-linecap="round"/><path d="M95 146 Q112 154 130 145" fill="none" stroke="#78463e" stroke-width="3" stroke-linecap="round"/><path d="M45 246 Q110 215 178 246" fill="none" stroke="#f4c927" stroke-width="2" opacity=".25"/></svg>`
}

function readiness(){const m=[];if(state.readDocs.size<2)m.push('قراءة محضرين');if(state.analyzedEvidence.size<4)m.push('تحليل 4 أحراز');if(state.askedQuestions.size<4)m.push('4 أسئلة استجواب');if(!state.contradictions.size)m.push('تثبيت تناقض');return{ready:m.length===0,missing:m}}
function progress(){const c=currentCase();if(!c)return 0;const docs=Math.min(1,state.readDocs.size/2)*20,ev=Math.min(1,state.analyzedEvidence.size/4)*35,qs=Math.min(1,state.askedQuestions.size/6)*25,co=state.contradictions.size?10:0,th=$('#theorySuspect')?.value&&$('#theoryMotive')?.value&&$('#theoryMethod')?.value?10:0;return Math.min(100,Math.round(docs+ev+qs+co+th))}
function updateHUD(){if(!CASES.length)return;$('#points').textContent=state.points.toLocaleString('ar-EG');$('#rank').textContent=rankFor(state.points);$('#solvedCount').textContent=`${Math.min(state.casesSolved,CASES.length)}/${CASES.length}`;const p=progress();$('#progressLabel').textContent=p+'%';$('#progressMeter').style.width=p+'%';const r=readiness();$('#caseMiniStatus').textContent=r.ready?'ملف الاتهام جاهز. انتقل إلى «بناء الاتهام».':`المطلوب: ${r.missing.join(' • ')}`}

function renderDashboard(){const c=currentCase();if(!c)return;$('#caseScope').textContent=c.scope;$('#caseNumber').textContent=`CASE ${String(state.index+1).padStart(2,'0')} / ${String(CASES.length).padStart(2,'0')}`;$('#caseCategory').textContent=c.category;$('#caseTitle').textContent=c.title;$('#caseMeta').textContent=`${c.city} • ${c.level}`;$('#caseBrief').textContent=c.brief;$('#caseDifficulty').textContent=c.difficulty+'%';$('#caseReward').textContent=c.reward.toLocaleString('ar-EG');$('#caseStatus').textContent=state.index<state.casesSolved?'مغلقة سابقًا':state.solved?'مغلقة':'نشطة';$('#factVictim').textContent=c.victim;$('#factLocation').textContent=c.location;$('#factTime').textContent=c.time;$('#factObjective').textContent=c.objective;$('#timeline').innerHTML=c.timeline.map(([t,x])=>`<div class="timeline-item"><div class="timeline-time">${esc(t)}</div><p>${esc(x)}</p></div>`).join('');const stages=[['المعاينة',state.inspectedHotspots.size>=2,'افحص نقطتين'],['المحاضر',state.readDocs.size>=2,'اقرأ وثيقتين'],['المعمل',state.analyzedEvidence.size>=4,'حلل 4 أحراز'],['الاستجواب',state.askedQuestions.size>=4,'اسأل 4 أسئلة'],['الاتهام',state.solved,'أغلق القضية']];$('#roadmap').innerHTML=stages.map(([n,d,s],i)=>`<div class="roadmap-step ${d?'done':(!d&&stages.slice(0,i).every(x=>x[1])?'current':'')}"><i></i><strong>${n}</strong><span>${d?'تمت المرحلة':s}</span></div>`).join('');$('#roadmapHint').textContent=state.solved?'القضية مغلقة':readiness().ready?'الملف جاهز للاتهام':'استكمل مراحل التحقيق'}
function renderScene(){const c=currentCase();$('#sceneIntro').textContent=c.sceneIntro;$('#sceneHotspots').innerHTML=c.hotspots.map((h,i)=>`<button type="button" class="scene-hotspot ${state.inspectedHotspots.has(i)?'found':''}" data-hotspot="${i}" aria-label="فحص ${esc(h.label)}">${i+1}</button>`).join('');$('#sceneVictimMarker').textContent=c.location}
function inspectHotspot(i){const h=currentCase().hotspots[i];if(!h)return;state.inspectedHotspots.add(i);$('#sceneFindingTitle').textContent=h.label;$('#sceneFindingText').textContent=h.detail;$('#sceneFindingTag').textContent=h.tag;renderScene();updateHUD();renderDashboard()}

function renderDocuments(){const c=currentCase();$('#documentList').innerHTML=c.documents.map((d,i)=>`<button type="button" class="document-btn ${state.readDocs.has(i)?'read':''}" data-doc="${i}"><strong>${esc(d.title)}</strong><span><em>${esc(d.type)}</em><em class="doc-status">${state.readDocs.has(i)?'تمت القراءة':'فتح الملف'}</em></span></button>`).join('');$('#docsReadCount').textContent=state.readDocs.size}
function openDocument(i){const d=currentCase().documents[i];if(!d)return;state.readDocs.add(i);$('#documentType').textContent=d.type;$('#documentTitle').textContent=d.title;$('#documentContent').textContent=d.content;$('#documentFooter').textContent=d.footer;renderDocuments();updateHUD();renderDashboard()}

function renderEvidence(){const c=currentCase();$('#evidenceGrid').innerHTML=c.evidence.map(e=>`<article class="evidence-item ${state.analyzedEvidence.has(e.id)?'analyzed':''}"><div class="evidence-top"><span class="evidence-code">${e.id.toUpperCase()}</span><span class="evidence-type">${esc(e.type)}</span></div><h3>${esc(e.name)}</h3><p>${esc(e.summary)}</p><div class="evidence-meta"><div><b>مكان الضبط:</b> ${esc(e.location)}</div><div><b>سلسلة الحيازة:</b> ${esc(e.chain)}</div></div><button type="button" class="${state.analyzedEvidence.has(e.id)?'ghost-btn':'primary-btn'} compact" data-analyze="${e.id}">${state.analyzedEvidence.has(e.id)?'عرض النتيجة':'تحليل الحرز'}</button></article>`).join('');$('#evidenceAnalyzedCount').textContent=state.analyzedEvidence.size}
function analyzeEvidence(id){const e=currentCase().evidence.find(x=>x.id===id);if(!e)return;state.analyzedEvidence.add(id);if(e.key)state.theoryEvidence.add(id);$('#labTitle').textContent=`${e.id.toUpperCase()} — ${e.name}`;$('#labResult').textContent=e.analysis;renderEvidence();renderTheoryEvidence();updateHUD();renderDashboard()}

function renderSuspects(){const c=currentCase();$('#suspectGrid').innerHTML=c.suspects.map((s,i)=>`<button type="button" class="suspect-card-v2 ${state.selectedSuspect===s.name?'selected':''}" data-suspect="${i}"><div class="portrait-3d">${avatarSVG(s)}</div><div class="suspect-card-body"><h3>${esc(s.name)}</h3><p>${esc(s.role)} • ${s.age} سنة</p><div class="risk-row"><span>مستوى الاشتباه</span><strong>${esc(s.risk)}</strong></div></div></button>`).join('');let idx=c.suspects.findIndex(s=>s.name===state.selectedSuspect);if(idx<0)idx=0;showSuspectDetail(idx,false)}
function showSuspectDetail(i,select=true){const s=currentCase().suspects[i];if(!s)return;if(select)state.selectedSuspect=s.name;$('#suspectDetail').innerHTML=`<div class="portrait-3d">${avatarSVG(s)}</div><div><span class="section-kicker">SUSPECT DOSSIER</span><h3>${esc(s.name)}</h3><p>${esc(s.bio)}</p><div class="suspect-facts"><div><span>الدافع المحتمل</span><strong>${esc(s.motive)}</strong></div><div><span>الحجة الزمنية</span><strong>${esc(s.alibi)}</strong></div><div><span>التناقض</span><strong>${esc(s.contradiction)}</strong></div></div><div class="hero-actions"><button type="button" class="primary-btn compact" data-interrogate="${i}">بدء الاستجواب</button></div></div>`;$$('.suspect-card-v2').forEach((b,n)=>b.classList.toggle('selected',n===i));updateHUD()}

const QB=[{id:'where',label:'أين كنت وقت الجريمة؟',keys:['اين','فين','مكان','كنت']},{id:'timeline',label:'اشرح لي التوقيت بالتفصيل',keys:['وقت','توقيت','ساعه','خرجت','وصلت','متى']},{id:'victim',label:'ما طبيعة علاقتك بالمجني عليه؟',keys:['علاقه','تعرف','ضحيه','مجني']},{id:'motive',label:'هل كان لديك دافع؟',keys:['دافع','سبب','خلاف','مال','فلوس','مصلحه']},{id:'evidence',label:'كيف تفسر الأدلة ضدك؟',keys:['دليل','ادله','حرز','بطاقه','كاميرا','بصمه','سجل','حقيبه']},{id:'contact',label:'متى كان آخر تواصل بينكما؟',keys:['تواصل','مكالمه','رساله','كلمت','اتصلت','اخر مره']}];
function norm(t){return String(t||'').toLowerCase().replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي').replace(/[ًٌٍَُِّْ]/g,'')}
function classify(t){const n=norm(t);let best=QB[4],score=0;for(const q of QB){let s=0;q.keys.forEach(k=>{if(n.includes(norm(k)))s++});if(s>score){score=s;best=q}}return best}
function renderInterrogation(){const c=currentCase();$('#interrogationSuspect').innerHTML=c.suspects.map((s,i)=>`<option value="${i}">${esc(s.name)} — ${esc(s.role)}</option>`).join('');let idx=c.suspects.findIndex(s=>s.name===state.selectedSuspect);if(idx<0)idx=0;$('#interrogationSuspect').value=idx;setInterrogationSuspect(idx,false);$('#questionsAskedCount').textContent=state.askedQuestions.size}
function setInterrogationSuspect(i,clear=true){const s=currentCase().suspects[i];if(!s)return;state.selectedSuspect=s.name;$('#interrogationPortrait').innerHTML=avatarSVG(s);const stress=Math.min(95,s.stress+state.askedQuestions.size*5);$('#stressMeter').style.width=stress+'%';$('#stressLabel').textContent=stress>65?'متوتر':stress>35?'متحفظ':'هادئ';const found=state.contradictions.has(s.name);$('#contradictionBox').className='contradiction-box'+(found?' found':'');$('#contradictionBox').textContent=found?'تناقض مثبت: '+s.contradiction:'لم يتم تثبيت تناقض بعد.';$('#suggestedQuestions').innerHTML=QB.map(q=>`<button type="button" class="question-chip" data-question="${q.id}">${q.label}</button>`).join('');if(clear||!$('#chatLog').children.length)$('#chatLog').innerHTML=`<div class="chat-message answer"><small>${esc(s.name)}</small>أنا جاهز. اسأل اللي عايز تعرفه.</div>`;updateHUD()}
function askQuestion(text,id=null){const idx=Number($('#interrogationSuspect').value||0),s=currentCase().suspects[idx],q=id?QB.find(x=>x.id===id):classify(text);if(!s||!q)return;state.askedQuestions.add(`${state.index}:${s.name}:${q.id}`);if((q.id==='timeline'||q.id==='evidence')&&s.contradiction&&!s.contradiction.startsWith('لا يوجد'))state.contradictions.add(s.name);const ans=s.answers[q.id]||'لا أملك إضافة على ما قلته.';$('#chatLog').insertAdjacentHTML('beforeend',`<div class="chat-message question"><small>المحقق</small>${esc(text||q.label)}</div><div class="chat-message answer"><small>${esc(s.name)}</small>${esc(ans)}</div>`);$('#chatLog').scrollTop=$('#chatLog').scrollHeight;$('#questionsAskedCount').textContent=state.askedQuestions.size;setInterrogationSuspect(idx,false);renderDashboard()}

function renderTheoryEvidence(){const c=currentCase(),items=[...state.theoryEvidence].map(id=>c.evidence.find(e=>e.id===id)).filter(Boolean);$('#theoryEvidence').innerHTML=items.length?items.map(e=>`<span class="theory-clue">${e.id.toUpperCase()} • ${esc(e.name)}</span>`).join(''):'<span class="micro-copy">حلّل الأدلة الأساسية ليتم إضافتها تلقائيًا إلى سلسلة الاستنتاج.</span>'}
function renderTheory(){const c=currentCase();$('#theorySuspect').innerHTML='<option value="">اختر المشتبه</option>'+c.suspects.map(s=>`<option>${esc(s.name)}</option>`).join('');$('#theoryMotive').innerHTML='<option value="">اختر الدافع</option>'+c.motives.map(x=>`<option>${esc(x)}</option>`).join('');$('#theoryMethod').innerHTML='<option value="">اختر الطريقة</option>'+c.methods.map(x=>`<option>${esc(x)}</option>`).join('');if(state.selectedSuspect)$('#theorySuspect').value=state.selectedSuspect;renderTheoryEvidence();renderReadiness()}
function renderReadiness(){const rows=[['قراءة محضرين على الأقل',state.readDocs.size>=2],['تحليل أربعة أحراز',state.analyzedEvidence.size>=4],['طرح أربعة أسئلة استجواب',state.askedQuestions.size>=4],['اكتشاف تناقض في الأقوال',state.contradictions.size>0],['اختيار المشتبه + الدافع + الطريقة',Boolean($('#theorySuspect').value&&$('#theoryMotive').value&&$('#theoryMethod').value)]];$('#readinessChecklist').innerHTML=rows.map(([t,d])=>`<div class="ready-item ${d?'done':''}">${t}</div>`).join('');updateHUD()}
function showAcc(msg,ok=false){const b=$('#accusationMessage');b.textContent=msg;b.className='accusation-message'+(ok?' success':'')}
async function saveProfile(){if(window.gameAuth)await window.gameAuth.savePlayerState({points:state.points,rank:rankFor(state.points),currentCase:state.index,casesSolved:state.casesSolved})}
async function submitAccusation(){const c=currentCase(),r=readiness();if(!r.ready){showAcc('ملف الاتهام غير مكتمل. استكمل: '+r.missing.join('، '));return}const suspect=$('#theorySuspect').value,motive=$('#theoryMotive').value,method=$('#theoryMethod').value;if(!suspect||!motive||!method){showAcc('اختر المشتبه والدافع والطريقة.');return}const ok=suspect===c.correct.suspect&&motive===c.correct.motive&&method===c.correct.method;if(!ok){state.wrongAttempts++;state.points=Math.max(0,state.points-120);showAcc('الفرضية غير متماسكة مع كل الأدلة. خُصم 120 نقطة. راجع التوقيت والتناقضات.');updateHUD();await saveProfile();return}const already=state.index<state.casesSolved,bonus=Math.max(0,180-state.wrongAttempts*60-(state.hintUsed?50:0)),earned=already?0:c.reward+bonus;if(!already){state.points+=earned;state.casesSolved=Math.max(state.casesSolved,state.index+1)}state.solved=true;showAcc('اتهام صحيح. تم إغلاق القضية.',true);updateHUD();renderDashboard();renderCaseSelector();if(window.gameAuth){await window.gameAuth.saveCaseProgress(state.index,true,earned);await saveProfile()}$('#caseSolvedTitle').textContent=state.index===CASES.length-1?'تم إنهاء الموسم الأول':'تم إغلاق القضية';$('#caseSolvedText').textContent=c.conclusion;$('#caseSolvedScore').textContent=already?'القضية مغلقة سابقًا — لا نقاط إضافية':`مكافأة القضية ${c.reward} + مكافأة الأداء ${bonus} = ${earned} نقطة`;$('#continueNextCase').textContent=state.index<CASES.length-1?'الانتقال للقضية التالية':'مراجعة خريطة القضايا';$('#caseSolvedModal').classList.remove('hidden')}
async function continueNext(){ $('#caseSolvedModal').classList.add('hidden'); if(state.index<CASES.length-1){state.index++;resetCaseState();await saveProfile();renderAll();setView('dashboard')}else setView('league') }

function renderCaseSelector(){const el=$('#caseSelector');el.innerHTML=CASES.map((c,i)=>{const unlocked=i<=state.casesSolved,solved=i<state.casesSolved;return `<button type="button" class="case-selector-btn ${i===state.index?'current':''} ${unlocked?'':'locked'}" data-case="${i}" ${unlocked?'':'disabled'}><span class="case-index">${String(i+1).padStart(2,'0')}</span><span><strong>${esc(c.title)}</strong><small>${esc(c.city)} • ${esc(c.scope)} • صعوبة ${c.difficulty}%</small></span><em>${solved?'مغلقة':i===state.casesSolved?'متاحة':'مقفلة'}</em></button>`}).join('')}
async function selectCase(i){if(i>state.casesSolved)return;state.index=i;resetCaseState();await saveProfile();renderAll();setView('dashboard')}
async function refreshLeaderboard(){const el=$('#leaderboard');if(!window.gameAuth?.loadLeaderboard){el.innerHTML='<div class="loading-line">سجل الدخول لعرض الترتيب.</div>';return}el.innerHTML='<div class="loading-line">جارٍ تحميل الترتيب...</div>';const rows=await window.gameAuth.loadLeaderboard(10);el.innerHTML=rows.length?rows.map((r,i)=>`<div class="leader-row"><span class="place">${i+1}</span><span><strong>${esc(r.username)}</strong><small>${esc(r.country||'غير محدد')} • ${esc(r.rank||rankFor(r.points||0))}</small></span><strong>${Number(r.points||0).toLocaleString('ar-EG')}</strong></div>`).join(''):'<div class="loading-line">لا توجد بيانات ترتيب بعد.</div>'}
function renderAll(){if(!CASES.length)return;renderDashboard();renderScene();renderDocuments();renderEvidence();renderSuspects();renderInterrogation();renderTheory();renderCaseSelector();updateHUD()}
function hydrate(p={}){state.points=Math.max(0,Number(p.points)||0);state.casesSolved=Math.min(CASES.length,Math.max(0,Number(p.cases_solved)||0));state.index=Math.min(CASES.length-1,Math.max(0,Number(p.current_case)||0));if(state.index<state.casesSolved&&state.casesSolved<CASES.length)state.index=state.casesSolved;resetCaseState();renderAll();setView('dashboard')}

$$('.ops-nav').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.go)));
$('#sceneHotspots').addEventListener('click',e=>{const b=e.target.closest('[data-hotspot]');if(b)inspectHotspot(Number(b.dataset.hotspot))});
$('#documentList').addEventListener('click',e=>{const b=e.target.closest('[data-doc]');if(b)openDocument(Number(b.dataset.doc))});
$('#evidenceGrid').addEventListener('click',e=>{const b=e.target.closest('[data-analyze]');if(b)analyzeEvidence(b.dataset.analyze)});
$('#suspectGrid').addEventListener('click',e=>{const b=e.target.closest('[data-suspect]');if(b)showSuspectDetail(Number(b.dataset.suspect))});
$('#suspectDetail').addEventListener('click',e=>{const b=e.target.closest('[data-interrogate]');if(b){setView('interrogation');$('#interrogationSuspect').value=b.dataset.interrogate;setInterrogationSuspect(Number(b.dataset.interrogate),true)}});
$('#interrogationSuspect').addEventListener('change',e=>setInterrogationSuspect(Number(e.target.value),true));
$('#suggestedQuestions').addEventListener('click',e=>{const b=e.target.closest('[data-question]');if(b){const q=QB.find(x=>x.id===b.dataset.question);askQuestion(q.label,q.id)}});
$('#questionForm').addEventListener('submit',e=>{e.preventDefault();const i=$('#questionInput'),t=i.value.trim();if(!t)return;askQuestion(t);i.value=''});
['theorySuspect','theoryMotive','theoryMethod'].forEach(id=>$('#'+id).addEventListener('change',()=>{state.selectedSuspect=$('#theorySuspect').value||state.selectedSuspect;renderReadiness()}));
$('#submitAccusation').addEventListener('click',submitAccusation);$('#hintBtn').addEventListener('click',async()=>{if(!state.hintUsed){state.hintUsed=true;state.points=Math.max(0,state.points-50);await saveProfile()}$('#hintText').textContent=currentCase().hint;updateHUD()});
$('#continueNextCase').addEventListener('click',continueNext);$('#reviewClosedCase').addEventListener('click',()=>$('#caseSolvedModal').classList.add('hidden'));
$('#caseSelector').addEventListener('click',e=>{const b=e.target.closest('[data-case]');if(b&&!b.disabled)selectCase(Number(b.dataset.case))});$('#refreshLeaderboard').addEventListener('click',refreshLeaderboard);
window.addEventListener('player-ready',e=>hydrate(e.detail?.profile||{}));
resetCaseState();renderAll();if(window.gameAuth?.profile)hydrate(window.gameAuth.profile);
