-- من القاتل؟ - Player database schema
-- جميع الجداول في public محمية بـ Row Level Security.

create table if not exists public.player_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 2 and 80),
  username text not null unique check (username ~ '^[A-Za-z0-9_\-]{3,24}$'),
  country text not null default 'غير محدد' check (char_length(country) between 2 and 60),
  points integer not null default 0 check (points >= 0),
  rank text not null default 'محقق مبتدئ',
  current_case integer not null default 0 check (current_case >= 0),
  cases_solved integer not null default 0 check (cases_solved >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.game_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  case_index integer not null check (case_index >= 0),
  solved boolean not null default false,
  earned_points integer not null default 0 check (earned_points >= 0),
  solved_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(user_id, case_index)
);

alter table public.player_profiles enable row level security;
alter table public.game_progress enable row level security;

-- Grants المطلوبة للـ Data API.
grant select, insert, update on public.player_profiles to authenticated;
grant select, insert, update on public.game_progress to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- اللاعب المسجل يستطيع مشاهدة ملفات اللاعبين العامة اللازمة للترتيب.
drop policy if exists "authenticated can read player profiles" on public.player_profiles;
create policy "authenticated can read player profiles"
on public.player_profiles for select
to authenticated
using (true);

-- اللاعب يستطيع إنشاء ملفه فقط.
drop policy if exists "player can insert own profile" on public.player_profiles;
create policy "player can insert own profile"
on public.player_profiles for insert
to authenticated
with check ((select auth.uid()) = id);

-- اللاعب يستطيع تعديل ملفه فقط.
drop policy if exists "player can update own profile" on public.player_profiles;
create policy "player can update own profile"
on public.player_profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

-- تقدم اللاعب خاص به فقط.
drop policy if exists "player can read own progress" on public.game_progress;
create policy "player can read own progress"
on public.game_progress for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "player can insert own progress" on public.game_progress;
create policy "player can insert own progress"
on public.game_progress for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "player can update own progress" on public.game_progress;
create policy "player can update own progress"
on public.game_progress for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create index if not exists player_profiles_points_idx
  on public.player_profiles(points desc);

create index if not exists game_progress_user_idx
  on public.game_progress(user_id, case_index);
