(()=>{
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], esc=t=>String(t??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
const S={index:0,points:0,solved:0,selected:0,docs:new Set(),evidence:new Set(),questions:new Set(),contradictions:new Set(),wrong:0};
const qbank=[["where","أين كنت وقت الجريمة؟"],["relation","ما علاقتك بالضحية؟"],["motive","هل لديك دافع لقتلها؟"],["evidence","ما تفسيرك لهذا الدليل؟"],["timeline","اشرح توقيت تحركاتك"],["contact","متى كان آخر تواصل؟"]];
const c=()=>CaseEngine.get(S.index);
function rank(p){if(p>100000)return"أسطورة التحقيق";if(p>50000)return"محقق مخضرم";if(p>20000)return"خبير جنائي";if(p>8000)return"محقق أول";if(p>2500)return"محقق ميداني";return"محقق متدرب"}
function reset(){S.selected=0;S.docs.clear();S.evidence.clear();S.questions.clear();S.contradictions.clear();S.wrong=0;$("#accusationMsg").textContent="";$("#hintText").textContent=""}
function setView(v){$$(".view").forEach(x=>x.classList.add("hidden"));$("#view-"+v)?.classList.remove("hidden");$$("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===v));if(v==="interrogate")renderInterrogation();if(v==="theory")renderTheory();if(v==="map")renderMap();if(v==="league")renderLeague();window.scrollTo({top:0,behavior:"smooth"})}
function header(){const cc=c();$("#caseTitle").textContent=cc.title;$("#caseNo").textContent=`القضية ${cc.index+1} من ${CaseEngine.total}`;$("#locationTop").textContent=`${cc.city} • ${cc.country}`;$("#points").textContent=S.points.toLocaleString("ar-EG");$("#rank").textContent=rank(S.points);$("#attempts").textContent=`${S.solved} / ${CaseEngine.total}`;$("#difficulty").textContent=cc.difficulty+"%"}
function renderScene(){const cc=c();$("#sceneImg").src=gameAsset(cc.sceneImage);$("#caseBrief").textContent=cc.brief;$("#victim").textContent=cc.victim;$("#casePlace").textContent=cc.location;$("#caseTime").textContent=cc.time}
function renderSuspects(){const cc=c();const html=cc.suspects.map((s,i)=>`<button class="sus-card ${i===S.selected?"active":""}" data-suspect="${i}"><img src="${gameAsset("assets/portraits/p"+String(s.portrait).padStart(2,"0")+".png")}" alt="${esc(s.name)}"><strong>${esc(s.name)}</strong><span>${esc(s.role)}</span><small>نسبة الاشتباه <b>${s.risk==="مرتفع"?"72":s.risk==="متوسط"?"48":"27"}%</b></small></button>`).join("");setAll(".suspect-strip",html)}
function setAll(sel,html){$$(sel).forEach(x=>x.innerHTML=html)}
function renderEvidence(){const cc=c();const html=cc.evidence.map(e=>`<button class="ev-card ${S.evidence.has(e.id)?"done":""}" data-evidence="${e.id}"><img src="${gameAsset(e.image)}"><span>${esc(e.name)}</span><small>${e.code}</small></button>`).join("");setAll(".evidence-grid",html);$("#evidenceCount").textContent=cc.evidence.length}
function renderDocs(){const cc=c();$("#docList").innerHTML=cc.documents.map((d,i)=>`<button class="${S.docs.has(i)?"read":""}" data-doc="${i}"><strong>${esc(d.title)}</strong><span>${esc(d.type)}</span></button>`).join("")}
function openDoc(i){const d=c().documents[i];S.docs.add(i);$("#docView").innerHTML=`<span>سري للغاية</span><h2>${esc(d.title)}</h2><p>${esc(d.body)}</p>`;renderDocs()}
function analyze(id){const e=c().evidence.find(x=>x.id===id);S.evidence.add(id);$("#labResult").innerHTML=`<strong>${esc(e.name)}</strong><p>${esc(e.result)}</p>`;renderEvidence()}
function renderInterrogation(){const s=c().suspects[S.selected];$("#interrogatePerson").innerHTML=`<img src="${gameAsset("assets/portraits/p"+String(s.portrait).padStart(2,"0")+".png")}"><h3>${esc(s.name)}</h3><p>${esc(s.role)}</p><small>${esc(s.alibi)}</small>`;$("#questionButtons").innerHTML=qbank.map(q=>`<button data-q="${q[0]}">${q[1]}</button>`).join("");$("#contradiction").textContent=S.contradictions.has(s.id)?"تم اكتشاف تناقض: توقيته لا يطابق السجل المصحح.":"لم يتم اكتشاف تناقض مؤكد بعد."}
function ask(id,text){const s=c().suspects[S.selected];S.questions.add(`${s.id}-${id}`);if((id==="timeline"||id==="evidence")&&s.risk==="مرتفع")S.contradictions.add(s.id);$("#chat").insertAdjacentHTML("beforeend",`<div class="me">${esc(text)}</div><div class="them"><b>${esc(s.name)}</b>${esc(s.answers[id])}</div>`);$("#chat").scrollTop=$("#chat").scrollHeight;renderInterrogation()}
function ready(){const x=[];if(S.docs.size<2)x.push("اقرأ محضرين");if(S.evidence.size<4)x.push("حلل 4 أحراز");if(S.questions.size<4)x.push("اسأل 4 أسئلة");if(!S.contradictions.size)x.push("اكتشف تناقضًا");return x}
function renderTheory(){const cc=c();$("#who").innerHTML='<option value="">اختر المشتبه</option>'+cc.suspects.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("");$("#why").innerHTML='<option value="">اختر الدافع</option>'+cc.motives.map(x=>`<option>${esc(x)}</option>`).join("");$("#how").innerHTML='<option value="">اختر الطريقة</option>'+cc.methods.map(x=>`<option>${esc(x)}</option>`).join("");const miss=ready();$("#readiness").innerHTML=(miss.length?miss:["ملف الاتهام جاهز"]).map(x=>`<div>${esc(x)}</div>`).join("")}
async function accuse(){const cc=c(),miss=ready();if(miss.length)return $("#accusationMsg").textContent="استكمل: "+miss.join("، ");if($("#who").value!==cc.correct.suspectId||$("#why").value!==cc.correct.motive||$("#how").value!==cc.correct.method){S.points=Math.max(0,S.points-120);S.wrong++;header();return $("#accusationMsg").textContent="الاتهام غير صحيح. راجع الأدلة والتوقيت."}const earned=cc.reward+Math.max(0,150-S.wrong*40);if(S.index>=S.solved){S.points+=earned;S.solved=S.index+1}header();await gameAuth?.saveCaseProgress(S.index,true,earned);await save();$("#solvedText").textContent=cc.conclusion;$("#solvedPoints").textContent=`+${earned.toLocaleString("ar-EG")} نقطة`;$("#modal").classList.remove("hidden")}
async function next(){if(S.index<CaseEngine.total-1){S.index++;reset();renderAll();await save();setView("case")}else setView("map");$("#modal").classList.add("hidden")}
async function save(){await gameAuth?.savePlayerState({points:S.points,rank:rank(S.points),currentCase:S.index,casesSolved:S.solved})}
function renderMap(){const start=Math.floor(S.index/40)*40;$("#caseMap").innerHTML=CaseEngine.range(start,40).map(cc=>`<button data-case="${cc.index}" ${cc.index>S.solved?"disabled":""} class="${cc.index===S.index?"current":""} ${cc.index<S.solved?"solved":""}"><b>${cc.index+1}</b><span>${esc(cc.title)}</span><small>${esc(cc.city)} • ${cc.difficulty}%</small></button>`).join("")}
async function renderLeague(){const rows=await gameAuth?.loadLeaderboard?.()||[];$("#leaderboard").innerHTML=rows.map((r,i)=>`<div><b>${i+1}</b><span><strong>${esc(r.username)}</strong><small>${esc(r.country||"")}</small></span><em>${Number(r.points||0).toLocaleString("ar-EG")}</em></div>`).join("")||"<p>لا توجد بيانات بعد.</p>"}
function renderAll(){header();renderScene();renderSuspects();renderEvidence();renderDocs();renderTheory()}
document.addEventListener("click",e=>{const v=e.target.closest("[data-view]");if(v)return setView(v.dataset.view);const s=e.target.closest("[data-suspect]");if(s){S.selected=Number(s.dataset.suspect);renderSuspects();return}const ev=e.target.closest("[data-evidence]");if(ev)return analyze(ev.dataset.evidence);const d=e.target.closest("[data-doc]");if(d)return openDoc(Number(d.dataset.doc));const q=e.target.closest("[data-q]");if(q){const item=qbank.find(x=>x[0]===q.dataset.q);return ask(item[0],item[1])}const cse=e.target.closest("[data-case]");if(cse&&!cse.disabled){S.index=Number(cse.dataset.case);reset();renderAll();setView("case")}});
$("#questionForm").onsubmit=e=>{e.preventDefault();const t=$("#questionInput").value.trim();if(!t)return;ask("evidence",t);$("#questionInput").value=""};
$("#accuseBtn").onclick=accuse;$("#nextBtn").onclick=next;document.getElementById("nextBtnModal").onclick=next;$("#reviewBtn").onclick=()=>$("#modal").classList.add("hidden");$("#hintBtn").onclick=()=>{$("#hintText").textContent="قارن توقيت الكاميرا بسجل الدخول، ثم اسأل المشتبه الأعلى خطورة عن الدليل والتوقيت."};
window.addEventListener("player-ready",e=>{const p=e.detail.profile||{};S.points=Number(p.points)||0;S.solved=Number(p.cases_solved)||0;S.index=Math.min(CaseEngine.total-1,Number(p.current_case)||0);if(S.index<S.solved&&S.solved<CaseEngine.total)S.index=S.solved;reset();renderAll()});
renderAll();
})();